language: python
dist: xenial

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls

# command to run tests
script:
   pytest --cov=pyod/

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - hongzuoxu@126.com
  on_success: never # default: change
  on_failure: always # default: always
